PRESETS = {
    "None": {
        "scale": "Major",
        "key": "A",
        "octave": 2,
        "harmony": "None",
        "randomize_octaves": True,
        "resize_to_n_pixels": False,
        "t_value": 0.2,
        "n_pixels": 64,
        "gain_db": 0.0,
        "drive_db": 0.0,
        "cutoff_hz": 0.0,
        "resonance_lad": 0.0,
        "drive_lad": 1.0,
        "delay_seconds": 0.0,
        "room_size": 0.0,
        "damping": 0.0,
        "wet_level": 0.0,
        "dry_level": 0.1,
        "width": 0.0,
        "rate_hz_chorus": 0.0,
    },
    "Bitcrusher": {
        "scale": "Natural Minor",
        "key": "G",
        "octave": 2,
        "harmony": "Perfect fifth",
        "randomize_octaves": True,
        "resize_to_n_pixels": False,
        "t_value": 0.1,
        "n_pixels": 100,
        "gain_db": 9.0,
        "drive_db": 14.0,
        "cutoff_hz": 81.0,
        "resonance_lad": 0.4,
        "drive_lad": 5.8,
        "delay_seconds": 0.0,
        "room_size": 0.1,
        "damping": 0.0,
        "wet_level": 0.0,
        "dry_level": 0.3,
        "width": 0.0,
        "rate_hz_chorus": 0.0,
    },
    "Sleepy Silly Penguin": {
        "scale": "Dorian",
        "key": "F",
        "octave": 3,
        "harmony": "Major third",
        "randomize_octaves": False,
        "t_value": 0.22,
        "n_pixels": 143,
        "gain_db": 0.0,
        "drive_db": 0.0,
        "cutoff_hz": 0.0,
        "resonance_lad": 0.0,
        "drive_lad": 1.0,
        "delay_seconds": 0.0,
        "room_size": 0.0,
        "damping": 0.0,
        "wet_level": 0.0,
        "dry_level": 0.1,
        "width": 0.0,
        "rate_hz_chorus": 0.3,
    },
    "Underground Cave": {
        "scale": "Mixolydian",
        "key": "C",
        "octave": 2,
        "harmony": "Major sixth",
        "randomize_octaves": False,
        "t_value": 0.2,
        "n_pixels": 219,
        "gain_db": 0.0,
        "drive_db": 0.0,
        "cutoff_hz": 0.0,
        "resonance_lad": 0.2,
        "drive_lad": 1.0,
        "delay_seconds": 0.1,
        "room_size": 0.2,
        "damping": 0.3,
        "wet_level": 0.0,
        "dry_level": 0.1,
        "width": 0.0,
        "rate_hz_chorus": 1.4,
    },
    "Distorted Bass": {
        "scale": "Aeolian",
        "key": "A#",
        "octave": 1,
        "harmony": "None",
        "randomize_octaves": False,
        "t_value": 0.3,
        "n_pixels": 64,
        "gain_db": 12.0,
        "drive_db": 4.0,
        "cutoff_hz": 0.0,
        "resonance_lad": 0.2,
        "drive_lad": 1.0,
        "delay_seconds": 0.0,
        "room_size": 0.1,
        "damping": 0.0,
        "wet_level": 0.0,
        "dry_level": 0.6,
        "width": 0.0,
        "rate_hz_chorus": 0.0,
    },
    "Bitcrusher (re:)": {
        "scale": "Natural Minor",
        "key": "G",
        "octave": 3,
        "harmony": "Major seventh",
        "randomize_octaves": True,
        "t_value": 0.1,
        "n_pixels": 100,
        "gain_db": 9.0,
        "drive_db": 14.0,
        "cutoff_hz": 81.0,
        "resonance_lad": 0.4,
        "drive_lad": 5.8,
        "delay_seconds": 0.0,
        "room_size": 0.1,
        "damping": 0.0,
        "wet_level": 0.0,
        "dry_level": 0.3,
        "width": 0.0,
        "rate_hz_chorus": 0.0,
    },
}
